// Generated by gencpp from file air_lab4/ExecuteTstResponse.msg
// DO NOT EDIT!


#ifndef AIR_LAB4_MESSAGE_EXECUTETSTRESPONSE_H
#define AIR_LAB4_MESSAGE_EXECUTETSTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace air_lab4
{
template <class ContainerAllocator>
struct ExecuteTstResponse_
{
  typedef ExecuteTstResponse_<ContainerAllocator> Type;

  ExecuteTstResponse_()
    : success(false)
    , error_message()  {
    }
  ExecuteTstResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteTstResponse_

typedef ::air_lab4::ExecuteTstResponse_<std::allocator<void> > ExecuteTstResponse;

typedef boost::shared_ptr< ::air_lab4::ExecuteTstResponse > ExecuteTstResponsePtr;
typedef boost::shared_ptr< ::air_lab4::ExecuteTstResponse const> ExecuteTstResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::air_lab4::ExecuteTstResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::air_lab4::ExecuteTstResponse_<ContainerAllocator1> & lhs, const ::air_lab4::ExecuteTstResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_message == rhs.error_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::air_lab4::ExecuteTstResponse_<ContainerAllocator1> & lhs, const ::air_lab4::ExecuteTstResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace air_lab4

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fe914479ce03184a758c3f6990c928f";
  }

  static const char* value(const ::air_lab4::ExecuteTstResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fe914479ce03184ULL;
  static const uint64_t static_value2 = 0xa758c3f6990c928fULL;
};

template<class ContainerAllocator>
struct DataType< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "air_lab4/ExecuteTstResponse";
  }

  static const char* value(const ::air_lab4::ExecuteTstResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success            # Whether the execution was succesful\n"
"string error_message    # Error message if the execution was unsuccessful\n"
"\n"
;
  }

  static const char* value(const ::air_lab4::ExecuteTstResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteTstResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::air_lab4::ExecuteTstResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::air_lab4::ExecuteTstResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIR_LAB4_MESSAGE_EXECUTETSTRESPONSE_H
