// Generated by gencpp from file air_lab3/ExecuteTst.msg
// DO NOT EDIT!


#ifndef AIR_LAB3_MESSAGE_EXECUTETST_H
#define AIR_LAB3_MESSAGE_EXECUTETST_H

#include <ros/service_traits.h>


#include <air_lab3/ExecuteTstRequest.h>
#include <air_lab3/ExecuteTstResponse.h>


namespace air_lab3
{

struct ExecuteTst
{

typedef ExecuteTstRequest Request;
typedef ExecuteTstResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteTst
} // namespace air_lab3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::air_lab3::ExecuteTst > {
  static const char* value()
  {
    return "44f7b4ced43e85a05e62b2b38ffc3b46";
  }

  static const char* value(const ::air_lab3::ExecuteTst&) { return value(); }
};

template<>
struct DataType< ::air_lab3::ExecuteTst > {
  static const char* value()
  {
    return "air_lab3/ExecuteTst";
  }

  static const char* value(const ::air_lab3::ExecuteTst&) { return value(); }
};


// service_traits::MD5Sum< ::air_lab3::ExecuteTstRequest> should match
// service_traits::MD5Sum< ::air_lab3::ExecuteTst >
template<>
struct MD5Sum< ::air_lab3::ExecuteTstRequest>
{
  static const char* value()
  {
    return MD5Sum< ::air_lab3::ExecuteTst >::value();
  }
  static const char* value(const ::air_lab3::ExecuteTstRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::air_lab3::ExecuteTstRequest> should match
// service_traits::DataType< ::air_lab3::ExecuteTst >
template<>
struct DataType< ::air_lab3::ExecuteTstRequest>
{
  static const char* value()
  {
    return DataType< ::air_lab3::ExecuteTst >::value();
  }
  static const char* value(const ::air_lab3::ExecuteTstRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::air_lab3::ExecuteTstResponse> should match
// service_traits::MD5Sum< ::air_lab3::ExecuteTst >
template<>
struct MD5Sum< ::air_lab3::ExecuteTstResponse>
{
  static const char* value()
  {
    return MD5Sum< ::air_lab3::ExecuteTst >::value();
  }
  static const char* value(const ::air_lab3::ExecuteTstResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::air_lab3::ExecuteTstResponse> should match
// service_traits::DataType< ::air_lab3::ExecuteTst >
template<>
struct DataType< ::air_lab3::ExecuteTstResponse>
{
  static const char* value()
  {
    return DataType< ::air_lab3::ExecuteTst >::value();
  }
  static const char* value(const ::air_lab3::ExecuteTstResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIR_LAB3_MESSAGE_EXECUTETST_H
